### ISSUE TITLE
Mochiypop vs Mochiypop P

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/MochiyPop-E#2]
It appears that `Mochiypop P` is intended as a proportional version of `Mochiypop`. However, this functionality can easily be merged into a single file using the `.full` (for default proportional glyphs) and `.palt` (proportional alternative widths – for default full width glyphs) naming conventions in Glyphs. Can you merge these two fonts together? 

Note – It appears that `Mochiypop` has components preserved. I'd like to keep them.

**Comment by aaronbell** [comment]
Once the fonts are merged, I will conduct a full review :)

**Comment by fontdasu** [comment]
Mochiypop is a standard font made for WEB Fonts and editorials, but Mochiypop P is made as a proportional font so that it can be used as a font for Youtube movies and other applications such as Adobe Premiere.

Applications such as Adobe Premiere cannot be used for metric kerning, so I thought it would be easier to use them as proportional fonts.

I don't know how to merge these into one Glyphs file. I don't think I can.

**Comment by fontdasu** [comment]
I'm sorry. After re-examining this, I felt like I could merge it.

However, even if I merge them, I don't know how to export them individually.

**Comment by aaronbell** [comment]
My suggestion is not to use metric kerning, but OpenType substitutions. 

So like in Latin you have:
`a` and `a.full`

For the kana, you'd have:
`a-hira` and `a-hira.palt`

And the `a-hira.palt` is the proportional Mochiypop P version. Then in the Glyphs feature code, it'll create a `palt` feature that allows you to swap between the normal, fullwidth version of the kana and the proportional one. 

The only question is that I'm not sure of Adobe Premier's support for OpenType. I *think* it does, but will need to confirm. If not, then yes, we'll need to export a proportional version of the font. However, in that case, I'm going to split the common and non common bits between two Glyphs sources and merge them on build (again, not something you need to worry about—I'll take care of it) so that we (and you) don't have two near identical sources to manage.

**Comment by fontdasu** [comment]
I have Adobe Premiere and do movie editing, but it doesn't support OpenType proportions.
Also, neither PowerPoint nor Keynote support OpenType proportions.

As you say, I have two sources in one.

**Comment by fontdasu** [comment]
This time I will stop making Mochiypop P.

Management requires a lot of resources

This is because if I stick to Mochipyop P, I will not be able to release fonts.

I delete the source of Mochiypop P.

**Comment by aaronbell** [comment]
I made some modifications to the font file that I think you'll appreciate. From the existing MochiyPopP file on my desktop, I imported all of the glyphs (I think) that have proportional variants as `.palt` into MochiyPop, and converted them to components. That way any modifications made to the base forms will reflect there as well. 

Additionally, I set up a build script that generates a standard `Mochiy Pop One` (the "One" is per Google's naming convention), and also a `Mochiy Pop P One` version where the the sidebearings from the `.palt` variants are copied to the base forms. That way we can produce both in one build script, with a single master source 😄 

Please take a look at the font files in the new branch that I created: https://github.com/fontdasu/Mochiypop/tree/prepped

**Comment by fontdasu** [comment]
I'm just starting out with GitHub and I'm still not sure about registering or merging your branches, so I'm looking into it. please wait.

**Comment by fontdasu** [comment]
I was able to pull the files from the branch you created and merge the files :)

I imported .palts into MochiyPop and confirmed that I converted them to components.

Great work!
If I were to do the same thing, I would have taken the time to do it manually.

It feels very good.

**Comment by aaronbell** [comment]
Excellent! I will close this as fixed :)
