### ISSUE TITLE
Font needs to be resized

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/MochiyPop-E#3]
The [Google vertical metrics specification](https://github.com/googlefonts/gf-docs/tree/master/Spec#cjk-vertical-metrics) states that the winDescent value must be -288, and that no glyph can be deeper than that value in order to avoid risk of clipping. In Mochiypop, there are several glyphs that exceed that value:

under Ccedilla
under ccedilla
under p
under thorn
under q
under p.full
under q.full
under exclamdown
under questiondown
under underscore
under cedillacomb
under cedilla

The deepest is questiondown at -346. As such, I suggest scaling the font by 20% (or at 80% in the Glyphs transformations pane) to ensure that all glyphs remain within the BBox.

**Comment by fontdasu** [comment]
I understand the contents. Start fixing.

**Comment by fontdasu** [comment]
I fixed the glyph so that it doesn't exceed the winDescent value -288. Please check the latest file.

**Comment by aaronbell** [comment]
Will do, thanks!

**Comment by aaronbell** [comment]
It looks good. I found a couple of glyphs that still exceeded 288 by a point or two (and added a bottom extreme to the cedilla, which brought it in line), and fixed them. So good to go here :)
