### ISSUE TITLE
Anchor use inconsistent

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/MochiyPop-E#4]
There are anchors present in the Kana set, but not in the Latins. Given that the extended Latin glyphs are made from combining mark and base form components, adding anchors will help with rendering.

**Comment by fontdasu** [comment]
I don't know what the anchor is.

I made the kana set and the Latin set in the same way, so I don't understand why the Latin set doesn't have an anchor.

I want you to tell me a little more

**Comment by aaronbell** [comment]
Ah, sorry, I was confused by the presence of the `LSB` and `RSB` marks in the Kana:
<img width="555" alt="MochiyPop_glyphs_-_Mochiy_Pop" src="https://user-images.githubusercontent.com/8460297/98472485-39a0e480-21a8-11eb-97a3-3b346bb002fe.png">

Glyphs calls these 'anchors' but they don't mean the same thing as anchors in Latin. Sorry for being a bother!
