### ISSUE TITLE
Vendor ID appears not to be registered

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/MochiyPop-E#5]
Can you confirm that your vendorID,`FTDS`, is [registered with Microsoft](https://docs.microsoft.com/en-us/typography/vendors/)? And if it isn't, please file a request.

**Comment by fontdasu** [comment]
I don't register my vendor ID with Microsoft.

Delete the vendor ID if you don't need it.

**Comment by aaronbell** [comment]
I do need it. And I need it to be registered with Microsoft. Can you do so? :)

Here's the info:

>To register or update your Vendor ID, e-mail the following information to mstwsite@microsoft.com.
> 
>     Vendor ID (Required)
>         The Vendor ID you'd like to register (The four-character identifier for the vendor of the given type face - certain combinations can't be accepted)
> 
>     Foundry Name (Required)
>         The name of the foundry you are attempting to register.
> 
>     E-mail Address
>         The e-mail address will not be shared publicly or to anyone outside of Microsoft.
>         It will be used only as needed to maintain the vendor registry. For example, if changes are requested to an existing ID, this e-mail address will be used to verify the request with the foundry.
> 
>     Website
>         Link to the foundry website. This will be hyperlinked to the foundry name.
>         This is not required but does help others with contacting the font foundry associated with a vendor ID.

**Comment by fontdasu** [comment]
Yes.

As you say, I applied to Microsoft for a font vendor with the following content:

> Vendor ID (Required):
> FTDS
>
> Foundry Name (Required):
> FONTDASU
> 
> E-mail Address:
> fontdasu@gmail.com
> 
> Website:
> https://fontdasu.com/

**Comment by fontdasu** [comment]
Font vendor ID registration is complete.
The ID is FTDS.


`Hello,
 
Confirmation: Your ID FTDS is registered and listed in the registered typography vendors list.
Site: https://docs.microsoft.com/typography/vendors
 
Please verify the information and feel free to contact me if you have any questions or comments.
 
Thanks,
Ali `

**Comment by aaronbell** [comment]
Perfect. Thanks!
