### ISSUE TITLE
Please review the new branch `prepped`

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/MochiyPop-E#6]
Thank you for your feedback and support! Please take a look at the new branch [`prepped`](https://github.com/fontdasu/Mochiypop/tree/prepped) and let me know if the produced files meet your expectation. 

One thing to note—there is a bug in fonttools right now whereby vertical metrics are not being established correctly, so if you try vertical typesetting it'll look wrong. That should be resolved soon.

**Comment by aaronbell** [comment]
A couple of other things to note:
- Name has been updated to `Mochiy Pop One` per [Google's specification](https://github.com/googlefonts/gf-docs/tree/master/Spec#single-weight-families)
- Localized named aren't being added to the font as of yet due to a [bug in GlyphsLib](https://github.com/googlefonts/glyphsLib/issues/633)

**Comment by fontdasu** [comment]
I checked the file you created. Is no problem.

I merged the files.

Please check my repository.

By the way, I am fixing the glyph that the Latin word extremes misses.

The following files have been modified.

I want you to check.

> MochiyPop.glyphs
> I filed a glyph that extremes is missing.

**Comment by aaronbell** [comment]
Looks good. Thanks!
